[package]
name = "doji"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deno_core = "0.167.0"
deno_ops = "0.45.0"
swc_ecma_parser = "0.124.2"
